services:
  attack:
    image: aicnal/underattack:latest
    environment:
      - threshold
      - recover_threshold
      - high_duration
      - low_usage_duration
      - api_email
      - api_key
      - zone_id
    restart: unless-stopped
    volumes:
      - /proc:/host_proc:ro